import os

common_env = Environment()

include_paths = ['include']
lib_paths = [  ]

common_env.Append( CPPPATH = [ os.path.abspath(p) for p in include_paths ] )
#common_env.Append( CCFLAGS = ['-g','-Wall', '-DDEBUG', '-D__STDC_LIMIT_MACROS', '-D__STDC_FORMAT_MACROS' ] )
common_env.Append( CCFLAGS = ['-O3', '-m64', '-Wall','-DNDEBUG', '-D__STDC_LIMIT_MACROS', '-D__STDC_FORMAT_MACROS' ] )
common_env.Append( LIBS=[  'dl' ])
common_env.Append( LIBPATH=[ os.path.abspath(p) for p in lib_paths ] )


Export('common_env')
core_objs = SConscript( 'core/SConscript', 'common_env' )
mtl_objs = SConscript( 'mtl/SConscript', 'common_env' )
util_objs = SConscript( 'utils/SConscript', 'common_env' )

lib_objs = core_objs + mtl_objs + util_objs

common_env.Library( 'libminisat', lib_objs )
