import os, sys
import glob
common_env = Environment()
#senfutil.SetupForSENV(common_env)


include_paths = ['../../libdnnf/include', '../../']
lib_paths = [ '../../libdnnf', '../..', '../../mod-conformant-ff' ]

common_env.Append( CPPPATH = [ os.path.abspath(p) for p in include_paths ] )
common_env.Append( CCFLAGS = ['-g','-pg', '-O0', '-Wall', '-DDEBUG' ] )
#common_env.Append( CCFLAGS = ['-O3','-Wall','-DNDEBUG'] )
common_env.Append( LIBS=[ 'dl', 'dnnf', 'ff', 'nff', 'ff' ])
common_env.Append( LIBPATH=[ os.path.abspath(p) for p in lib_paths ] )

cxx_sources = Glob('*.cxx')
c_sources = Glob('*.c')

for s in cxx_sources:
    print s
src_objs = [ common_env.Object(s) for s in cxx_sources ] + [ common_env.Object(s) for s in c_sources ]


if src_objs is None : 
	print "src_objs is None"
	sys.exit(1)

common_env.Program( 'sqcorner', src_objs )
